//-----------------------------------------------------------------
//  Copyright © 2012 Schell Games, LLC. All Rights Reserved. 
//
//  Author: William Roberts
//  Date:   04/28/2011
//-----------------------------------------------------------------

using UnityEngine;
using System.IO;
using System;

namespace SG.Core
{
    /// <summary>
    /// Contains access to important paths within the Unity3D project.
    /// All paths are returned as a "Windows Friendly" absolute path
    /// on the local hard disk drive.
    /// </summary>
    public static class UnityPath
    {
        static UnityPath()
        {
            AssetsDirectory = AssetDirectoryUtility.AssetDirectory;

            // Normalize the assets path to be Windows friendly.
            if (Environment.OSVersion.Platform == PlatformID.MacOSX ||
                Environment.OSVersion.Platform == PlatformID.Unix)
            {
                AssetsDirectory = Application.dataPath;
            }
            else
            {
                AssetsDirectory = Application.dataPath.Replace('/', '\\');
            }

            var assetDirInfo = new DirectoryInfo(AssetsDirectory);
            if (assetDirInfo.Parent != null)
            {
                ProjectDirectory = assetDirInfo.Parent.FullName;
                ProjectName = assetDirInfo.Parent.Name;
            }
            else
                Log.Error("Unity project at filesystem root.");

            // These directories are relative to the project's directory.
            LibraryDirectory = Path.Combine(ProjectDirectory, LibraryDirectoryName);
            ProjectSettingsDirectory = Path.Combine(ProjectDirectory, ProjectSettingsDirectoryName);
            TempDirectory = Path.Combine(ProjectDirectory, TempDirectoryName);

            // This directory is relative to the assets directory
            AssetBundleConfigDirectory = Path.Combine(AssetsDirectory, BundlesDirectoryName);
        }

        /// <summary>
        /// Gets the projects "Assets" path.
        /// </summary>
        public static string AssetsDirectory { get; private set; }

        /// <summary>
        /// Gets the base project path.
        /// </summary>
        public static string ProjectDirectory { get; private set; }

        /// <summary>
        /// Gets the projects "Library" path. This directory typically
        /// contains temporary content that is generated by the UnityEditor.
        /// </summary>
        public static string LibraryDirectory { get; private set; }

        /// <summary>
        ///  Gets the projects "ProjectSettings" path. This directory contains
        ///  all of the Editor settings that should be uploaded to source control.
        /// </summary>
        public static string ProjectSettingsDirectory { get; private set; }

        /// <summary>
        /// Gets the path to the temporary directory. Note that Unity automatically
        /// deletes this directory when the project is closed.
        /// </summary>
        public static string TempDirectory { get; private set; }

        /// <summary>
        /// The path in which the Schell Games *.abc files reside within the project.
        /// </summary>
        public static string AssetBundleConfigDirectory { get; private set; }

        /// <summary>
        /// Gets the name of the currently opened project.
        /// </summary>
        public static string ProjectName { get; private set; }

        private const string BundlesDirectoryName = "Bundles";
        private const string LibraryDirectoryName = "Library";
        private const string ProjectSettingsDirectoryName = "ProjectSettings";
        private const string TempDirectoryName = "Temp";

        private static readonly Notify Log = NotifyManager.GetInstance("Core");
    }
}
